--? 1. MODELO DE DATOS – ORACLE 19c
--? Tabla de Nodos (Ciudades)
CREATE TABLE NODOS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100)
);

COMMIT;

--? Tabla de Aristas (Carreteras)
CREATE TABLE ARISTAS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORIGEN NUMBER,
    DESTINO NUMBER,
    DISTANCIA NUMBER,
    FOREIGN KEY (ORIGEN) REFERENCES NODOS(ID),
    FOREIGN KEY (DESTINO) REFERENCES NODOS(ID)
);

COMMIT;