--? 1. MODELO DE DATOS – ORACLE 19c
--? Tabla de Nodos (Ciudades)
CREATE TABLE NODOS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100)
);

COMMIT;

--? Tabla de Aristas (Carreteras)
CREATE TABLE ARISTAS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORIGEN NUMBER,
    DESTINO NUMBER,
    DISTANCIA NUMBER,
    FOREIGN KEY (ORIGEN) REFERENCES NODOS(ID),
    FOREIGN KEY (DESTINO) REFERENCES NODOS(ID)
);

COMMIT;

-- datos: 
INSERT INTO NODOS (NOMBRE) VALUES ('Madrid');
INSERT INTO NODOS (NOMBRE) VALUES ('Barcelona');
INSERT INTO NODOS (NOMBRE) VALUES ('Valencia');
INSERT INTO NODOS (NOMBRE) VALUES ('Sevilla');
INSERT INTO NODOS (NOMBRE) VALUES ('Zaragoza');
INSERT INTO NODOS (NOMBRE) VALUES ('Bilbao');
INSERT INTO NODOS (NOMBRE) VALUES ('Malaga');
INSERT INTO NODOS (NOMBRE) VALUES ('Murcia');
INSERT INTO NODOS (NOMBRE) VALUES ('Valladolid');
INSERT INTO NODOS (NOMBRE) VALUES ('Alicante');

COMMIT;

-- DESDE MADRID
INSERT INTO ARISTAS (ORIGEN, DESTINO, DISTANCIA)
VALUES (
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Madrid'),
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Barcelona'),
    620
);

INSERT INTO ARISTAS (ORIGEN, DESTINO, DISTANCIA)
VALUES (
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Madrid'),
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Valencia'),
    360
);

INSERT INTO ARISTAS (ORIGEN, DESTINO, DISTANCIA)
VALUES (
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Madrid'),
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Sevilla'),
    530
);

INSERT INTO ARISTAS (ORIGEN, DESTINO, DISTANCIA)
VALUES (
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Madrid'),
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Zaragoza'),
    320
);

INSERT INTO ARISTAS (ORIGEN, DESTINO, DISTANCIA)
VALUES (
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Madrid'),
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Bilbao'),
    400
);

INSERT INTO ARISTAS (ORIGEN, DESTINO, DISTANCIA)
VALUES (
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Madrid'),
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Valladolid'),
    220
);

-- BARCELONA
INSERT INTO ARISTAS (ORIGEN, DESTINO, DISTANCIA)
VALUES (
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Barcelona'),
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Zaragoza'),
    300
);

INSERT INTO ARISTAS (ORIGEN, DESTINO, DISTANCIA)
VALUES (
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Barcelona'),
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Valencia'),
    350
);

-- VALENCIA
INSERT INTO ARISTAS (ORIGEN, DESTINO, DISTANCIA)
VALUES (
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Valencia'),
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Murcia'),
    230
);

INSERT INTO ARISTAS (ORIGEN, DESTINO, DISTANCIA)
VALUES (
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Valencia'),
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Alicante'),
    170
);

-- ANDALUCIA
INSERT INTO ARISTAS (ORIGEN, DESTINO, DISTANCIA)
VALUES (
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Sevilla'),
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Malaga'),
    210
);

-- NORTE
INSERT INTO ARISTAS (ORIGEN, DESTINO, DISTANCIA)
VALUES (
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Bilbao'),
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Valladolid'),
    280
);

-- ESTE
INSERT INTO ARISTAS (ORIGEN, DESTINO, DISTANCIA)
VALUES (
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Murcia'),
    (SELECT ID FROM NODOS WHERE NOMBRE = 'Alicante'),
    80
);

COMMIT;

SELECT * FROM ARISTAS;